### ISSUE TITLE
"Secret" API key

### ISSUE THREAD

**Issue by RitwikGupta** [apjaffe/Sighting#1]
application.py line 16 has your AWS key exposed

**Comment by jroggeman** [comment]
Hey all, it looks like you pushed a commit to remove the key, but I can still go back to a previous commit and see it (and more malicious people will likely be more willing to do that).

I'd check out [this link](https://help.github.com/articles/remove-sensitive-data/) on how to purge sensitive data like keys from all commits, and re-generate the AWS key as well if you can.

**Comment by ghost** [comment]
Deleted all AWS keys. Thanks.
